### ISSUE TITLE
wang15_mplbl.mgz vs. wang15_fplbl.mgz

### ISSUE THREAD

**Issue by nblauch** [noahbenson/neuropythy#18]
hi Noah, thanks for the great package. i'm transitioning from your docker occipital_atlas container to the python `atlas` function and slightly confused about the wang 2015 outputs. what is the difference between `wang15_mplbl` and `wang15_fplbl`

thanks,
-nick

**Comment by noahbenson** [comment]
Hi Nick,
The `wang15_mplbl` atlas is the Wang _et al_. (2015) maximum probability atlas: for each vertex, the value assigned to it is the number of the visual area label that was most likely across the subjects they examined in the paper. The `wang15_fplbl` gives the full probability atlas from the paper. In the full probability atlas, there are 25 values per vertex (this file contains a matrix of _n_ rows, one per vertex, by 25 columns, one per visual area label). For a single vertex, there are 25 values representing the 25 visual areas in the paper, and each cell of that vertex gives the probability that that vertex is in the relevant visual area. The mappings between column number and visual area number are the same as provided with the original paper; these data can be downloaded [here](https://scholar.princeton.edu/napl/resources).
The `mplbl` is what most people usually want to see--a set of visual area labels that can be used as a prediction of the visual areas in an individual subject. The `fplbl` data is more general though; in fact, the `mplbl` should equal `numpy.argmax(fplbl, axis=1) + 1`.

**Comment by nblauch** [comment]
thanks a lot. i noticed the `benson14_varea` atlas now contains some of the ROIs that were previously only in Wang (hV4, VO1, VO2, LO1, LO2, TO1, TO2, V3a, V3b). Are these just ported from the Wang atlas or is there somewhere else I can look for how you acquired these?

**Comment by noahbenson** [comment]
Those areas in the Benson maps are not ported from the Wang atlas—they are fit like the other areas. However, they shouldn't be trusted as we have not validated them and do not believe them to be particularly accurate. They were included in the fitting as a way to stabilize aspects of the fitting process in V1-V3 and are included more for transparency than because they are scientifically useful. My [2018 paper](https://doi.org/10.7554/eLife.40224) and the [OSF site](https://osf.io/knb5g/) that goes with it discuss the updates to the fitting procedure used to develop the new version of the Benson14 atlas.
