### ISSUE TITLE
Visible Deprecation Warning creating ndarray from ragged nested sequences

### ISSUE THREAD

**Issue by MarieStLaurent** [noahbenson/neuropythy#24]
Hello! 

When running `register_retinotopy`, I am getting the following Deprecation warning with `save_surface_files` : 

`VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  try:              u = np.asarray(u)
`

This is with numpy==1.21.0

Should I install an older version?

thank you!

Marie

**Comment by noahbenson** [comment]
Unfortunately, I can't really advise you on what to do here without more information. This might be caused by something strange in the input, or it might be something unrelated. Could you let me know whether the outputs produced by `register_retinotopy` look reasonable? And whether there is anything else unusual about the subject (does this happen with all subjects)?

**Comment by MarieStLaurent** [comment]
Thanks for your quick response! It's the first subject I try. 

I'm just starting with freesurfer (freshly installed, there's a learning curve...) so I might have done something weird when projecting my retino on a flat surface. 

Knowing that this isn't a typical warning is helpful though. I'll look at the output asap. Subject was processed with fmriprep, so the freesurfer data may not be standard (mri_vol2surf required a special --regheader argument).

**Comment by MarieStLaurent** [comment]
Quick update: at first glance, the output looks fine. I wonder if it's related to this issue: https://github.com/numpy/numpy/pull/15119

**Comment by noahbenson** [comment]
Hmm, okay, glad to hear it seems to work fine. Keep me updated if you notice anything off about the outputs! This kind of warning can be very benign, and, in fact, it may be coming from one of the libraries neuropythy uses and not from neuropythy itself (hard to tell at this point).

What worries me is that this warning should really only occur if the code is making an array that's ragged, and I can't recall anywhere that the code would try to do this (though possibly it does as a bug or that I'm forgetting). When I get a chance I'll update my numpy version and test this out myself—hopefully then I can trace the warning to its source in the neuropythy code and decide if it's my fault or someone else's 😊

I'll keep this issue open for now. I guess one thing that might be helpful to know is whether the warning appears quickly when you run the `register_retinotopy` command or whether it happens after the command has been running for awhile?

**Comment by MarieStLaurent** [comment]
Gosh I hope I'm not wasting your time! I get the warning when `save_surface_files` is executed. It appears twice (once per hemi), sometime after "Extracting ?H predicted mesh..." is printed

I first suspected this line: https://github.com/noahbenson/neuropythy/blob/842c347c02aed081770cbd9fc13e49e220cdb17c/neuropythy/commands/register_retinotopy.py#L501

But since I get two warnings, I assume it's triggered somewhere in the for loop on line 517 instead. 

I'll try downgrading numpy and see if it's still an issue.

**Comment by noahbenson** [comment]
Oh not at all! So I upgraded my numpy locally and was able to reproduce the warning. In fact, you can safely ignore this warning—it's coming from a library `pimms` (that I also maintain), and it happens when `pimms` tries to convert an object into a numpy array in order to test if the object *can* be converted into a numpy array. The warning arises because, at some point in the future, numpy will throw an error in certain cases where it currently succeeds.

I've made a small change to the library that prevent the error and will update it and `neuropythy` on PyPI in the next few weeks. For now you can just ignore it though! You needn't downgrade or anything.

**Comment by MarieStLaurent** [comment]
Thanks tons!! This is all very reassuring, I'm really grateful how quickly you were able to address this! 

Best,

Marie
